### ISSUE TITLE
Readd support for metrics

### ISSUE THREAD

**Issue by JCash** [defold/extender#289]
We want to hook up our metrics to a server again.

**Comment by britzl** [comment]
Related: https://github.com/defold/extender/issues/218

**Comment by ekharkunov** [comment]
In `split-docker` branch was added sending metrics to Stackdriver. Here is overview after adding integration and running test builds:
|Metric|Is tracked|Notes|
|------|---------------|-------|
|job.receive| ✅  || 
|job.requestSize| ⛔ || 
|job.sdkDownload| ✅  ||
|job.sdk| ✅  ||
|job.gradle.download| ✅  ||
|job.gradle.cacheSize| ⛔ || 
|job.cocoapods.install| ⛔ |MacOS instance doesn't send metrics to Stackdriver now|
|job.build| ✅  ||
|job.remoteBuild| ✅  |Need small fix to track right time because `build_async` works in thread|
|job.zip| ✅  | Not all instances tracked metrics. Only emsdk-3155, winsdk-2022|
|job.zipSize| ✅  | Not all instances tracked metrics. Only emsdk-3155, winsdk-2022|
|job.write| ✅  ||
|job.cache.upload| ✅  ||
|job.cache.uploadSize| ✅  |All zeroes (cache not enabled now)|
|job.cache.download| ✅  ||
|job.cache.downloadSize| ✅  |All zeroes (cache not enabled now)|
|gauge.service.sdk.get| ✅  | Select "count time series" in dashboard|
|gauge.service.gradle.get| ✅  ||
|counter.service.sdk.get.download| ✅  ||
|counter.service.sdk.get| ✅  ||
